### ISSUE TITLE
invalidated content

### ISSUE THREAD

**Issue by lqdung-lockon** [eccubevn/ec-cube#147]
invalid content

**Comment by nhpkhanh-lk** [comment]
## 概要(Overview)
`OWASP ZAP` と `WAPITI`というセキュリティテストツールを実行し、カートを追加際に `ProductClass`変数に関するエラーを発見した。

## 期待する内容(Expect)  or 要望 (Requirement)


## 再現手順(Procedure)
1. `OWASP ZAP`ツールで、以下のコマンドを実行
`curl "http://59.106.214.245/eccube4.0-pg/products/add_cart/1" -e "http://59.106.214.245/eccube4.0-pg/products/list?category_id=1" -d "quantity=%3Benv&product_id=1&ProductClass=default&_token=a4IB_TMNYbYVGRaySLeptoHJN3U2bx9q6ma8kclvU1E&classcategory_id1=on&classcategory_id2=on"`
2.  `500 HTTP error`との結果が出る
あるべきエラーが  4xx => (NG) 
詳細：
- Header 
```
POST http://59.106.214.245/eccube4.0-pg/products/add_cart/1 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Content-Length: 2239
Referer: http://59.106.214.245/eccube4.0-pg/products/list?category_id=1
Cookie: device_view=full; eccube=l33ggjuv55vabht3vgg1bdvor2
Host: 59.106.214.245
```
- Body:
```
quantity=%3Benv&product_id=1&ProductClass=default&_token=ofPSi1zdpYasTzr6sKshIOoDnn1Vqccj5B-35esuatI&classcategory_id1=on&classcategory_id2=on
```

- Response (see Ref log):
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 06 Sep 2018 07:39:00 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.20
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.1.20
Cache-Control: max-age=0, must-revalidate, private
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Length: 1312
Connection: close
Content-Type: text/html; charset=UTF-8
```

- Debug error:
```
"An exception occurred while executing 'SELECT t0.id AS id_1, t0.product_code AS product_code_2, t0.stock AS stock_3, t0.stock_unlimited AS stock_unlimited_4, t0.sale_limit AS sale_limit_5, t0.price01 AS price01_6, t0.price02 AS price02_7, t0.delivery_fee AS delivery_fee_8, t0.visible AS visible_9, t0.create_date AS create_date_10, t0.update_date AS update_date_11, t0.currency_code AS currency_code_12, t0.point_rate AS point_rate_13, t0.product_id AS product_id_14, t0.sale_type_id AS sale_type_id_15, t0.class_category_id1 AS class_category_id1_16, t0.class_category_id2 AS class_category_id2_17, t0.delivery_duration_id AS delivery_duration_id_18, t0.creator_id AS creator_id_19, t0.discriminator_type FROM dtb_product_class t0 WHERE t0.id = ? AND t0.discriminator_type IN ('productclass')' with params [\"default\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"default\"
```

### 環境 (environment)
+ EC-CUBE: 4.0 beta 2
+ PHP: 7.1.20
+ DB:
  - PostgreSQL 9.4

## 関連情報 (Ref)
```
["An exception occurred while executing 'SELECT t0.id AS id_1, t0.product_code AS product_code_2, t0.stock AS stock_3, t0.stock_unlimited AS stock_unlimited_4, t0.sale_limit AS sale_limit_5, t0.price01 AS price01_6, t0.price02 AS price02_7, t0.delivery_fee AS delivery_fee_8, t0.visible AS visible_9, t0.create_date AS create_date_10, t0.update_date AS update_date_11, t0.currency_code AS currency_code_12, t0.point_rate AS point_rate_13, t0.product_id AS product_id_14, t0.sale_type_id AS sale_type_id_15, t0.class_category_id1 AS class_category_id1_16, t0.class_category_id2 AS class_category_id2_17, t0.delivery_duration_id AS delivery_duration_id_18, t0.creator_id AS creator_id_19, t0.discriminator_type FROM dtb_product_class t0 WHERE t0.id = ? AND t0.discriminator_type IN ('productclass')' with params [\"default\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"default\"","/var/www/html/eccube4.0-pg/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php",99,"#0 /var/www/html/eccube4.0-pg/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(184): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /var/www/html/eccube4.0-pg/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(158): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 /var/www/html/eccube4.0-pg/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(943): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT t0.id AS...', Array)\n#3 /var/www/html/eccube4.0-pg/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(733): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.id AS...', Array, Array)\n#4 /var/www/html/eccube4.0-pg/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(751): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load(Array, NULL)\n#5 /var/www/html/eccube4.0-pg/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(460): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->loadById(Array)\n#6 /var/www/html/eccube4.0-pg/var/cache/prod/ContainerErcfbkz/EntityManager_9a5be93.php(88): Doctrine\\ORM\\EntityManager->find('Eccube\\\\Entity\\\\P...', Array, NULL, NULL)\n#7 /var/www/html/eccube4.0-pg/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(154): EntityManager_9a5be93->find('Eccube\\\\Entity\\\\P...', 'default', NULL, NULL)\n#8 /var/www/html/eccube4.0-pg/src/Eccube/Form/DataTransformer/EntityToIdTransformer.php(59): Doctrine\\ORM\\EntityRepository->find('default')\n#9 /var/www/html/eccube4.0-pg/vendor/symfony/form/Form.php(1069): Eccube\\Form\\DataTransformer\\EntityToIdTransformer->reverseTransform('default')\n#10 /var/www/html/eccube4.0-pg/vendor/symfony/form/Form.php(643): Symfony\\Component\\Form\\Form->normToModel('default')\n#11 /var/www/html/eccube4.0-pg/vendor/symfony/form/Form.php(572): Symfony\\Component\\Form\\Form->submit('default', true)\n#12 /var/www/html/eccube4.0-pg/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(108): Symfony\\Component\\Form\\Form->submit(Array, true)\n#13 /var/www/html/eccube4.0-pg/vendor/symfony/form/Form.php(498): Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler->handleRequest(Object(Symfony\\Component\\Form\\Form), Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 /var/www/html/eccube4.0-pg/src/Eccube/Controller/ProductController.php(376): Symfony\\Component\\Form\\Form->handleRequest(Object(Symfony\\Component\\HttpFoundation\\Request))\n#15 /var/www/html/eccube4.0-pg/vendor/symfony/http-kernel/HttpKernel.php(151): Eccube\\Controller\\ProductController->addCart(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Eccube\\Entity\\Product))\n#16 /var/www/html/eccube4.0-pg/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#17 /var/www/html/eccube4.0-pg/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#18 /var/www/html/eccube4.0-pg/index.php(54): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#19 {main}"] [POST, /eccube4.0-pg/products/add_cart/1, 115.78.160.139, http://59.106.214.245/eccube4.0-pg/products/list?category_id=&name=, Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36]
```

**Comment by hoand-vn** [comment]
invalid content
